'use client';
import {useState} from 'react';

const phone='07968225363';
const displayPhone='07968 22 53 63';
const testimonials=[
 ['Professional and reassuring','We were made to feel comfortable throughout. Everything was explained clearly and the aftercare was excellent.'],
 ['Excellent care','A calm, professional experience from start to finish. We felt supported before and after the procedure.'],
 ['Highly recommended','Experienced, efficient and caring. We were very pleased with the service and follow-up.']
];

export default function Home(){
 const [open,setOpen]=useState(false);
 return <main>
  <header className="header"><a className="brand" href="#top"><span className="mark">LC</span><span><b>Luton Circumcision</b><small>Experienced • Professional • Local</small></span></a><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">☰</button><nav className={open?'open':''}><a href="#about">About</a><a href="#procedure">Procedure</a><a href="#care">Aftercare</a><a href="#testimonials">Testimonials</a><a href="#contact">Contact</a></nav><a className="callTop" href={'tel:'+phone}>Call {displayPhone}</a></header>
  <section className="hero" id="top"><div className="heroShade"></div><div className="heroContent"><p className="eyebrow">CIRCUMCISION SERVICES IN LUTON</p><h1>Experienced care,<br/><em>closer to home.</em></h1><p className="lead">Professional circumcision services in Luton from an experienced practitioner with over 20 years of experience.</p><div className="actions"><a className="primary" href={'tel:'+phone}>Call to arrange an appointment</a><a className="secondary" href={'https://wa.me/44'+phone.slice(1)}>WhatsApp us</a></div><div className="trust"><span>✓ 20+ years' experience</span><span>✓ Careful aftercare</span><span>✓ Luton location</span></div></div><div className="heroCard"><span>Appointments in</span><strong>Luton</strong><p>Hitchin Rd<br/>Luton LU2 7UL</p><a href="#contact">Arrange an appointment →</a></div></section>
  <section className="intro" id="about"><div><p className="eyebrow dark">EXPERIENCE YOU CAN TRUST</p><h2>Professional, experienced and focused on your family's care.</h2></div><div className="introCopy"><p>With more than 20 years of experience, Luton Circumcision provides a professional service for families seeking circumcision in the Luton area.</p><p>Every appointment is approached with care and discretion, with clear guidance and ongoing aftercare available following the procedure.</p><div className="stats"><div><strong>20+</strong><span>Years' experience</span></div><div><strong>24/7</strong><span>Aftercare support</span></div><div><strong>1</strong><span>Local Luton location</span></div></div></div></section>
  <section className="procedure" id="procedure"><div className="sectionHead"><p className="eyebrow dark">THE PROCEDURE</p><h2>Clear, careful and straightforward.</h2><p>The procedure is carried out efficiently with an approach designed to minimise pain and discomfort, while keeping parents informed and reassured throughout.</p></div><div className="cards"><article><i>01</i><h3>Before your appointment</h3><p>Contact us to arrange a suitable appointment. We will provide the information you need beforehand and answer any initial questions.</p></article><article><i>02</i><h3>At the appointment</h3><p>The procedure is performed by an experienced circumcision practitioner using sterile, single-use equipment and careful professional techniques.</p></article><article><i>03</i><h3>Aftercare</h3><p>You will receive clear aftercare guidance and support following the procedure, so you know what to expect and who to contact if needed.</p></article></div></section>
  <section className="care" id="care"><div className="carePanel"><p className="eyebrow">AFTERCARE MATTERS</p><h2>Support doesn't end when the appointment does.</h2><p>Good aftercare is an important part of the service. Clear instructions are provided after the procedure, together with ongoing support should you have any concerns.</p><ul><li>Clear aftercare instructions</li><li>Support available after the procedure</li><li>Experienced guidance for parents and families</li></ul><a className="lightButton" href={'tel:'+phone}>Speak to us</a></div><div className="quote"><span>“</span><p>Care, experience and reassurance at every stage.</p></div></section>
  <section className="testimonials" id="testimonials"><div className="sectionHead"><p className="eyebrow dark">TESTIMONIALS</p><h2>Trusted by families.</h2></div><div className="reviews">{testimonials.map(([t,p])=><article key={t}><div className="stars">★★★★★</div><h3>{t}</h3><p>“{p}”</p></article>)}</div><p className="reviewNote">Sample presentation pending confirmation of approved testimonials from the existing Expert Circ website.</p></section>
  <section className="contact" id="contact"><div><p className="eyebrow">ARRANGE AN APPOINTMENT</p><h2>Get in touch.</h2><p>For appointments or further information, call or WhatsApp us and we'll be happy to help.</p></div><div className="contactBox"><a href={'tel:'+phone}><small>CALL</small><strong>{displayPhone}</strong></a><a href={'https://wa.me/44'+phone.slice(1)}><small>WHATSAPP</small><strong>Message us</strong></a><a href="mailto:info@expertcirc.co.uk"><small>EMAIL</small><strong>info@expertcirc.co.uk</strong></a><div><small>LOCATION</small><strong>Hitchin Rd, Luton LU2 7UL</strong></div></div></section>
  <footer><div className="footerBrand"><span className="mark">LC</span><div><b>Luton Circumcision</b><small>Hitchin Rd, Luton LU2 7UL</small></div></div><p>© 2026 Luton Circumcision. All rights reserved.</p><a className="built" href="https://diamantsolutions.co.uk" target="_blank" rel="noreferrer">Built by <b>Diamant Solutions</b><small>Websites • Systems • Automation</small></a></footer>
 </main>
}